
--

SELECT NOME FROM TALUNO;

SELECT Concat(COD_ALUNO,NOME) FROM TALUNO;
/*concatena colunas, igual ao "pipe" mostrado abaixo*/

SELECT COD_ALUNO || NOME FROM TALUNO;

SELECT COD_ALUNO ||' '|| NOME FROM TALUNO;

SELECT COD_ALUNO ||' - '|| NOME FROM TALUNO;

SELECT COD_ALUNO ||'. '|| NOME FROM TALUNO;

--

SELECT NOME, InitCap(NOME) FROM TALUNO;
/*Coloca a primeira letra em maiúsculo e as demais em minúsculas*/

SELECT NOME, InStr(NOME, 'R') FROM TALUNO;
/*mostra onde está determinado caractere escolhido, neste caso o R e informa a posição*/

SELECT NOME, Length(NOME) FROM TALUNO;
/*conta quantos caracteres tem*/

SELECT NOME, Lower(NOME) FROM TALUNO;
/*passa tudo para minúsculo == transforma só para mostrar no SELECT, para alterar é UPDATE*/

SELECT NOME, Upper(NOME) FROM TALUNO;
/*passa tudo para maiúsculo*/

--

SELECT InitCap('JOSÉ DA SILVA') FROM TALUNO;
SELECT InitCap('JOSÉ DA SILVA') FROM DUAL;

SELECT LPad(COD_ALUNO,5,'0') FROM TALUNO;
/*L de left - preenche à esquerda com 0 por 5x*/

SELECT NOME, SALARIO, RPad(SALARIO,8,'0') FROM TALUNO;
/*R de right - preenche à direita com 0 por 8x*/

SELECT NOME, RPad(NOME,10,'$') FROM TALUNO;

--

SELECT NOME, SubStr(NOME,1,3) FROM TALUNO;
/*copia parte de um texto*/
/*substr (campo/texto, apartir da posição x, quantidade caractere a serem copiados)*/

SELECT NOME, SubStr(NOME,1,1) FROM TALUNO;

SELECT NOME, SubStr(NOME,3,1) FROM TALUNO;

--

SELECT REPLACE(NOME,'R','$') FROM TALUNO;
/*substitui todas as letras R por $*/

SELECT REPLACE(InitCap(NOME),'R','_') FROM TALUNO;
/*não resulta em nada, pois o InitCap deixou a primeira em maiúscula
e as demais em minúsculas e como não temos R iniciando nenhum nome
nada apareceu. Os errer existentes estão minúsculos*/

SELECT REPLACE(Upper(NOME),'R','_') FROM TALUNO;
/*Ao passar todos para maiúscula, ele reconhece o 'R' e substitui
pelo '_' solicitado*/

SELECT REPLACE(InitCap(NOME),'A','EI') FROM TALUNO;

SELECT REPLACE(Upper(NOME),'A','EI') FROM TALUNO;

-- PARA MOSTRAR A ÚLTIMA LETRA  --

SELECT NOME, SubStr(NOME,Length(NOME),1) FROM TALUNO;
/*LENGTH(NOME) CONTA QUANTOS CARACTERES TEM*/
/*SUBSTR MOSTRA O CARACTERE NA POSIÇÃO, neste caso Length(NOME) POR 1X*/

SELECT NOME, SubStr(NOME,Length(NOME)-1,2) FROM TALUNO;
/*a contagem do length é a penultima por 2x, então mostra as 2 últimas letras*/

SELECT NOME, SubStr(NOME,3,Length(NOME)-3) FROM TALUNO;

--

SELECT * FROM TALUNO;

SELECT * FROM TALUNO
WHERE Lower(NOME) = 'marcio';

SELECT * FROM TALUNO
WHERE Upper(NOME) = 'MARCIO';

INSERT INTO TALUNO VALUES (10, 'TERESA', 'CANOAS', 90000101, 'RS', 1720, '23/02/1982');
INSERT INTO TALUNO VALUES (11, 'ADON', 'TUBARÃO', 88000200, 'SC', 1420, '24/04/1972');
INSERT INTO TALUNO VALUES (12, 'íSIS', 'CANOAS', 90000101, 'RS', 1720, '25/06/1962');
INSERT INTO TALUNO VALUES (13, 'PIMBO', 'CANOAS', 90000101, 'RS', 1220, '26/08/1952');
INSERT INTO TALUNO VALUES (14, 'ANDERSON', 'FLORIANÓPOLIS', 88045103, 'SC', 1720, '27/10/1982');
INSERT INTO TALUNO VALUES (15, 'YURI', 'CANOAS', 90000101, 'RS', 1720, '28/12/1942');
INSERT INTO TALUNO VALUES (16, 'UBALDO', 'VIAMÃO', 90000101, 'RS', 1020, '29/01/1992');
INSERT INTO TALUNO VALUES (17, 'WOLNEY', 'PORTO ALEGRE', 90000101, 'RS', 1720, '30/03/2002');
INSERT INTO TALUNO VALUES (18, 'IURY', 'CANOAS', 90000101, 'RS', 320, '01/05/1983');
INSERT INTO TALUNO VALUES (20, 'VANIA', 'PINHAL', 90000101, 'RS', 720, '02/07/1988');

SELECT * FROM TALUNO 
WHERE Upper(SubStr(CIDADE,1,3)) = 'CAN';

SELECT COD_ALUNO FROM TALUNO;

--

UPDATE TALUNO SET 
SALARIO = 633.47
WHERE COD_ALUNO = 1;

UPDATE TALUNO SET 
SALARIO = 2500.75
WHERE COD_ALUNO = 8;

--

SELECT 
    SALARIO,
    REPLACE(SALARIO, ',', ''),  /*substitui a vírgula de salário por nada*/
    RPad(SALARIO, 10, '0'),     /*coloca ZEROS a direita em até 10 casas*/
    LPad(SALARIO, 10, '0'),     /*coloca ZEROS a esquerda em até 10 casas*/
    LPad(REPLACE(SALARIO, ',', ''), 10, '0')
FROM TALUNO;    

--

SELECT * FROM DUAL;

-- SYSDATE retorna data/hora do Servidor  --

SELECT SYSDATE FROM DUAL;

-- ROUND e TRUNC  --

SELECT  ROUND(45.925, 2),       /*arredonda para cima*/
        TRUNC(45.929, 2),       /*arredonda para baixo, mostra a parte INTEIRA*/
        MOD(10, 2) AS RESTO_DIVISAO,
        TRUNC(1.99),
        TRUNC(1.99, 2)
FROM DUAL;

--

SELECT * FROM TCONTRATO;

-- FUNÇÕES DE DATA E HORA  --

select to_char(sysdate,'DD/MM/YYYY HH24:MI:SS') as Data_Hoje from dual;
/*maneira de configurar MÁSCARA para apresentação data e hora*/

/*
A maneira acima com a máscara no TO_CHAR foi a maneira encontrada de mostrar as horas
no SQL Developer sem procurar alguma configuração. O comando SELECT DATA, SYSDATE, DATA + 5 FROM TCONTRATO;
aparece sem a hora no mesmo. Porém o mesmo comando no SQLTools vem com o resultado contendo data/hora
09/04/2021 12:27:25 09/04/2021 14:27:25
*/

SELECT DATA, SYSDATE, DATA + 5 FROM TCONTRATO;
SELECT DATA, SYSDATE, to_char(DATA + 5,'DD/MM/YYYY HH24:MI:SS') FROM TCONTRATO;

/*
TESTANDO POSSIBILIDADE DE INCLUIR A MÁSCARA EM TODOS
SELECT to_char((DATA, SYSDATE, DATA + 5),'DD/MM/YYYY HH24:MI:SS') FROM TCONTRATO;
to_char(SELECT DATA, SYSDATE, DATA + 5,'DD/MM/YYYY HH24:MI:SS') FROM TCONTRATO
SELECT to_char(SYSDATE - DATA,'DD/MM/YYYY HH24:MI:SS') AS DIF_DIAS FROM TCONTRATO;
*/

SELECT TRUNC(SYSDATE - DATA) AS DIAS FROM TCONTRATO;
SELECT to_char(sysdate,'DD/MM/YYYY HH24:MI:SS'), DATE, TRUNC(SYSDATE - DATA) AS DIAS FROM TCONTRATO;

SELECT SYSDATE + 2 / 24 AS ADD_HORAS FROM TCONTRATO;
/*somar horas em uma data*/
/*24 É A QUANTIDADE DE HORAS QUE TEM EM UM DIA*/

SELECT
    TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),
    TO_CHAR(SYSDATE + 2 / 24,'DD/MM/YYYY HH24:MI:SS') AS ADD_HORAS
FROM TCONTRATO;

SELECT SYSDATE + 15 / 1440 AS ADD_MINUTOS FROM TCONTRATO;
/*somar minutos em uma Data*/
/*1440 É A QUANTIDADE DE MINUTOS QUE TEM EM UM DIA*/

SELECT
    TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),
    TO_CHAR(SYSDATE + 15 / 1440,'DD/MM/YYYY HH24:MI:SS') AS ADD_MINUTOS
FROM TCONTRATO;

SELECT SYSDATE + 30 / (3600 * 24) AS ADD_SEGUNDOS FROM TCONTRATO;
/*somar segundos em uma Data*/
/*3600 É A QUANTIDADE DE SEGUNDOSS QUE TEM EM UMA HORA X 24 HORAS DE UM DIA*/

SELECT
    TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),
    TO_CHAR(SYSDATE + 30 / (3600 * 24),'DD/MM/YYYY HH24:MI:SS') AS ADD_SEGUNDOS
FROM TCONTRATO;

--  HORA FICA 00:00:00 --

SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'),Trunc(SYSDATE) FROM DUAL;

SELECT Months_Between (SYSDATE, SYSDATE-90) AS DIF_MES FROM DUAL;

SELECT Add_Months(SYSDATE, 5) AS ADICIONA_MES_DATA FROM DUAL;

SELECT NEXT_DAY(SYSDATE, 'QUARTA-FEIRA') AS PROXIMA_QUARTA_DATA FROM DUAL;

SELECT LAST_DAY(SYSDATE) AS ULTIMO_DIA_MES FROM DUAL;

SELECT ROUND(SYSDATE, 'MONTH') AS PRIMEIRO_DIA_PROXIMO_MES FROM DUAL;
-- ATÉ O DIA 15 DO MÊS CORRENTE ELE RETORNA O PRIMEIRO DIA DO MÊS ATUAL
-- A PARTIR DO DIA 16, ELE RETORNA O PRIMEIRO DIA DO PRÓXIMO MÊS

SELECT TRUNC(SYSDATE, 'MONTH') AS PRIMEIRO_DIA_MES_CORRENTE FROM DUAL;


-- FORMATAÇÃO DE DATA
-- Conversor TO_CHAR(DATA, FORMATO)

SELECT TO_CHAR(SYSDATE, 'DD') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY') DATA FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD/MM') DIA_MES FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD') DIA FROM DUAL;

SELECT TO_CHAR(SYSDATE,'MM') MES FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY') ANO_4_DIG FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YY') ANO_2_DIG FROM DUAL;

SELECT TO_CHAR(SYSDATE,'MONTH') MES1 FROM DUAL;
-- ESTA OPÇÃO ESCREVE O NOME DO MÊS

SELECT TO_CHAR(SYSDATE,'D') DIA_SEMANA FROM DUAL;
-- 1 É DOMINGO, 2 É SEGUNDA, 3 É TERÇA E ASSIM SEGUE...

SELECT TO_CHAR(SYSDATE,'DY') DIA_SEMANA FROM DUAL;
-- MOSTRA O DIA DA SEMANA, MAS A ABREVIATURA DO DIA
-- ASSIM UMA QUARTA-FEIRA SERÁ MOSTRADO QUA

SELECT TO_CHAR(SYSDATE,'DAY') DIA_SEMANA1 FROM DUAL;
-- MOSTRA O DIA DA SEMANA, MAS A O NOME DO DIA-FEIRA
-- ASSIM UMA QUARTA-FEIRA SERÁ MOSTRADO QUARTA-FEIRA

SELECT TO_CHAR(SYSDATE,'YEAR') ANO FROM DUAL;
-- SOLETRA O ANO CORRENTE, MAS EM INGL:ES
-- 2021 É TWENTY TWENTY-ONE

SELECT TO_CHAR(SYSDATE,'"FLORIANÓPOLIS,", fmDAY "," DD "de" fmMonth "de" YYYY"."') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'HH24:MI') HORA_MINUTO FROM DUAL;

SELECT TO_CHAR(SYSDATE,'HH24:MI:SS') HORA-MINUTO-SEGUNDO FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD/MM HH24:MI') DATA_HORA FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA_ANO_HORA FROM DUAL;

-- TO_CHAR também pode ser utilizado para formatar números
-- por exemplo, dinheiro

--L -> R$
--G -> ponto
--D -> casas decimais

SELECT * FROM TALUNO;

SELECT TO_CHAR(SALARIO,'L99999.99'), TO_CHAR(SALARIO,'L999G999D99') FROM TALUNO;

SELECT
    TO_CHAR(SALARIO,'L99999.99') SALARIO_01,
    TO_CHAR(SALARIO,'L999G999D99') SALARIO_02
FROM TALUNO;
-- A DIFERENÇA DESTE PARA O PRIMEIRO SÃO OS ALIAS PARA FACILITAR O ENTENDIMENTO DA INFORMAÇÃO

SELECT
    TRIM(TO_CHAR(SALARIO,'L99999.99')) SALARIO_01,
    TRIM(TO_CHAR(SALARIO,'L999G999D99')) SALARIO_02
FROM TALUNO;
-- A DIFERENÇA DESTE PARA O ANTERIOR É O TRIM QUE RETIRA OS ESPAÇOS E JOGA A INFORMAÇÃO P/ ESQUERDA

SELECTE 'R$ '||(ROUND(SALARIO,2)) AS SALARIO_03 FROM TALUNO;
-- UMA OUTRA MANEIRA DE COLOCAR O CIFRÃO, MAS NÃO ARRUMA CASAS DECIMAIS

--

SELECT LPad(TRIM((TO_CHAR(5000,'L99999.99'))),'12',' ') FROM DUAL;

SELECT 'R$ '||LPad((TO_CHAR(800,'99999.99')),'12',' ') FROM DUAL;

--

-- SELECT LPad((TO_CHAR(SALARIO,'L99999.99'),'12',' ')) FROM TALUNO;

SELECT 'R$ '||LPad((TO_CHAR(SALARIO,'99999.99')),'12',' ') FROM TALUNO;


-- NLV e NLV2

SELECT * FROM TCONTRATO;

SELECT  TOTAL,
        DESCONTO,
        DESCONTO+TOTAL,
        NVL(DESCONTO,0),
        NVL(DESCONTO,0) + TOTAL,
        NVL2(DESCONTO, TOTAL, -1)
FROM TCONTRATO;

-- 

UPDATE TALUNO SET
NOME = NULL
WHERE COD_ALUNO = 5;

SELECT COD_ALUNO, NVL(NOME, 'SEM NOME') FROM TALUNO;

--

SELECT * FROM TALUNO;

--UPDATE TALUNO SET
--ESTADO = 'AC'
--WHERE COD_ALUNO=2;

--UPDATE TALUNO SET
--ESTADO = 'SC'
--WHERE COD_ALUNO = 3;

--UPDATE TALUNO SET 
--ESTADO = 'RJ'
--WHERE COD_ALUNO = 5;

-- CASE

SELECT MOME, ESTADO,
    CASE
        WHEN ESTADO = 'RS' THEN 'GAUCHO'
        WHEN ESTADO = 'AC' THEN 'ACREANO'
        WHEN ESTADO = 'RJ' AND SALARIO > 500 THEN 'CARIOCA_TOP'
        WHEN ESTADO = 'RJ' AND SALARIO <= 500 THEN 'CARIOCA'
        WHEN ESTADO = 'SC' THEN 'BARRIGA VERDE'
        ELSE 'OUTROS'
    END AS APELIDO
FROM TALUNO;  

SELECT * FROM TALUNO;

SELECT SYSDATE AS DATA FROM DUAL;

SELECT NOME, ESTADO,
DECODE (ESTADO, 'RS','GAUCHO',
                'AC', 'ACREANO',
                'SP', 'PAULISTA',
                      'OUTROS'
        ) AS APELIDO
FROM TALUNO;

UPDATE TALUNO SET
ESTADO = 'AC',
CIDADE = 'RIO BRANCO'
WHERE COD_ALUNO = 18;

UPDATE TALUNO SET
ESTADO = 'AC',
CIDADE = 'RIO BRANCO'
WHERE COD_ALUNO = 9;

UPDATE TALUNO SET
ESTADO = 'AC',
CIDADE = 'RIO BRANCO'
WHERE COD_ALUNO = 13;





















































