
SELECT * FROM TALUNO;

<!-- ---- ALTER TABLE TALUNO DROP COLUMN COLUNA ---- -->

ALTER TABLE TALUNO ADD ESTADO CHAR(2) DEFAULT 'RS';
ALTER TABLE TALUNO ADD SALARIO NUMBER(8,2) DEFAULT 620;

UPDATE TALUNO SET 
ESTADO = 'AC', SALARIO = 250 
WHERE COD_ALUNO = 1;

UPDATE TALUNO SET 
ESTADO = 'MT', SALARIO = 2000
WHERE COD_ALUNO = 2;

UPDATE TALUNO SET 
ESTADO = 'SP', SALARIO = 800
WHERE COD_ALUNO = 5;

SELECT * FROM TALUNO;

COMMIT;

<!-- ----  ---- -->

SELECT * FROM TALUNO 

WHERE ESTADO <> 'RS'
AND SALARIO <= 800
ORDER BY SALARIO DESC;

INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE)
VALUES (SEQ_ALUNO.NEXTVAL, 'VALDO', 'DOIS IRMAOS');

INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE)
VALUES (SEQ_ALUNO.NEXTVAL, 'ALDO','QUATRO IRMAOS');

SELECT * FROM TALUNO;

UPDATE TALUNO SET 
ESTADO= 'SP', SALARIO = 900, NOME = 'PEDRO'
WHERE COD_ALUNO =5;

<!-- ----  ---- -->

SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;

<!-- ----
    31/12/1899 - DATA Zero
    01/01/1900 - DATA 1

    O DEFAULT UTILIZADO não é nada COMUM
    aqui só para os exemplos
---- -->

ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE - 1000;

SELECT SYSDATE - SYSDATE - 100 FROM DUAL;

SELECT * FROM TALUNO 

<!-- ----  ---- -->

UPDATE TALUNO SET 
NASCIMENTO='10/10/2001'
WHERE COD_ALUNO=1;

UPDATE TALUNO SET 
NASCIMENTO='10/08/2000'
WHERE COD_ALUNO=2

INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE, ESTADO)
VALUES (8, 'IURI','FLORIANOPOLIS', 'SC');

INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE)
VALUES (9, 'XITA','GONGO BELGA');

SELECT * FROM TALUNO 

UPDATE TALUNO SET 
NASCIMENTO='11/02/1970'
WHERE COD_ALUNO=8

UPDATE TALUNO SET 
NASCIMENTO='10/08/1917'
WHERE COD_ALUNO=9

<!-- ----  ---- -->

SELECT COD_ALUNO, NASCIMENTO, NASCIMENTO, NOME
FROM TALUNO 
WHERE NASCIMENTO = '21/05/2010';

SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM TALUNO 
WHERE Trunc(NASCIMENTO) = '21/05/2010';
/*o comando TRUNC arredonda... e no caso de data, ele retira as horas*/

SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM TALUNO 
WHERE NASCIMENTO
BETWEEN TO_DATE('21/05/2010 15:00','DD/MM/YYYY HH24:MI')
AND TO_DATE('21/05/2010 21:00','DD/MM/YYYY HH24:MI');

<!-- ----  ---- -->

SELECT * FROM TCONTRATO;

UPDATE TCONTRATO SET 
DESCONTO = NULL
WHERE COD_CONTRATO =2;

SELECT * FROM TCONTRATO 
WHERE DESCONTO IS NULL;

SELECT * FROM TCONTRATO 
WHERE DESCONTO IS NOT NULL;

SELECT * FROM TCONTRATO 
WHERE DESCONTO BETWEEN 0 AND 10;

<!-- ---- 
    NVL -- COLUNAS COM VALOR NULL
    neste caso o NVL pega valores NULL e transforma em ZERO
---- -->

SELECT COD_CONTRATO, TOTAL, DESCONTO, NVL(DESCONTO,0)
FROM TCONTRATO
WHERE NVL(DESCONTO,0) BETWEEN 0 AND 10;

<!-- ---- o mesmo efeito do BETWEEN ---- -->

SELECT * FROM TCONTRATO
WHERE DESCONTO >= 0
AND DESCONTO <= 10
OR DESCONTO IS NULL;

<!-- ---- IN /// NOT IN ---- -->

SELECT * FROM TITEM;

SELECT * FROM TITEM
WHERE COD_CURSO IN (1, 2, 4);

SELECT * FROM TITEM
WHERE COD_CURSO NOT IN (1, 2, 3);

SELECT * FROM TCURSO;

INSERT INTO TCURSO VALUES (5, 'WINDOWS', 1000, 50);

<!-- ----
COMPARANDO DADOS DE UMA TABELA COM BASE EM OUTRA TABELA
Podendo verificar os CURSOS NÃO VENDIDOS por exemplo    
---- -->

SELECT * FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM);

<!-- ---- ou verificar os cursos VENDIDOS ---- -->

SELECT * FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM);

<!-- ---- Podemos fazer o IN / NOT IN de outras maneiras  ---- -->

SELECT * FROM TITEM
WHERE COD_CURSO=1
OR COD_CURSO=2
OR COD_CURSO=4;

<!-- ---- Pode-se realizar filtros 9SELECT) conforme letra ou palavra desejada ---- -->

SELECT * FROM TCURSO WHERE NOME LIKE 'W%';
/*mostra apenas cursos iniciados com W*/

SELECT * FROM TCURSO WHERE NOME LIKE '%JAVA%';
/*retorna cursos que contenham JAVA*/

SELECT * FROM TCURSO WHERE NOME LIKE '%FACES';
/*retorna cursos que terminem com FACES*/

SELECT * FROM TCURSO WHERE NOME LIKE '_I%';
/*retorna cursos que contenham a letra I na segunda posição*/

<!-- ----  ---- -->

SELECT * FROM TCURSO;

COMMIT;

ALTER TABLE TCURSO ADD PRE_REQ INTEGER;
/*adiciona mais uma coluna na tabela de CURSO*/

UPDATE TCURSO SET 
PRE_REQ=1
WHERE COD_CURSO=2;

UPDATE TCURSO SET 
PRE_REQ=3
WHERE COD_CURSO=4;

<!-- ---- CURSOS SEM PRÉ REQUISITOS ---- -->

SELECT * FROM TCURSO WHERE PRE_REQ IS NULL;

<!-- ---- CURSOS COM PRÉ REQUISITOS ---- -->

SELECT * FROM TCURSO WHERE PRE_REQ IS NOT NULL

<!-- ---- PRESCEDÊNCIA DE OPERADORES ---- -->
/*a ordem são () parênteses, depois AND seguido de OR*/
/*abaixo 2 exemplos com e sem parênteses*/

SELECT * FROM TCURSO
WHERE VALOR > 750
OR VALOR < 1000
ANDE CARGA_HORARIA = 25;

SELECT * FROM TCURSO
WHERE (VALOR > 750
OR VALOR < 1000)
ANDE CARGA_HORARIA = 25;

<!--  -->



