-----------------------------------
-- CRIANDO E GERENCIANDO TABELAS --
-----------------------------------

CREATE TABLE TESTE (
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    DATA DATE DEFAULT SYSDATE
);
/*o SYSDATE indica que se nenhuma data for inserida na entrada de dados,
será assumida a data do momento*/

INSERT INTO TESTE (CODIGO) VALUES (1);

INSERT INTO TESTE (CODIGO, DATA) VALUES (2, '12/04/2021');

SELECT * FROM TESTE;

-- TABELAS CRIADAS PELO USUÁRIO --
SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES;

-- TABELAS CRIADAS A PARTIR DE UM SELECT DE OUTRA TABELA

CREATE TABLE TCONTRATO_VIP 
AS SELECT * FROM TCONTRATO WHERE TOTAL > 500;

SELECT * FROM TCONTRATO_VIP;

-- ADICIONAR COLUNA NA TABELA
ALTER TABLE TCONTRATO_VIP ADD VALOR3 NUMBER(5,2);

-- ALTERAR COLUNA
ALTER TABLE TCONTRATO_VIP MODIFY VALOR3 NUMBER(8,2);

ALTER TABLE TCONTRATO_VIP MODIFY VALOR3 NUMBER (13,2) DEFAULT 0;

-- RENOMEAR COLUNA
ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR3 TO VALOR2;

-- EXCLUIR COLUNA
ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

-- RENOMEAR TABELA
RENAME TCONTRATO_VIP TO TCONTRATO_TOP;

SELECT * FROM TCONTRATO_TOP;

RENAME TCONTRATO_TOP TO TCONTRATO_VIP;

SELECT * FROM TCONTRATO_VIP;

-- EXCLUIR TABELA
DROP TABLE TCONTRATO_VIP;

-- 
-- 
-- COMENTÁRIOS NA TABELA
COMMENT ON TABLE TCONTRATO IS 'Informações de Contratos';

-- COMENTÁRIOS NA TABELA
COMMENT ON TABLE TCONTRATO IS 'Informações de Contratos';

-- COMENTÁRIOS NA COLUNA DA TABELA
COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Código de Contrato';

COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de emissão do Contrato';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME='TCONTRATO';

SELECT * FROM USER_TAB_COMMENTS WHERE TABLE_NAME='TCONTRATO';

-- 
-- 
-- DESABILITA A COLUNA
ALTER TABLE TCONTRATO ADD TOTAL3 NUMERIC(8,2);

SELECT * FROM TCONTRATO;

ALTER TABLE TCONTRATO SET UNUSED (TOTAL3);
/*uma coluna desabilitada, não pode mais ser HABILITADA
O MÁXIMO QUE PODE FAZER É APAGAR UMA COLUNA DESABILITADA*/

-- EXCLUIR COLUNAS NÃO UTILIZADAS
ALTER TABLE TCONTRATO DROP UNUSED COLUMNS;

---
---
-- TRUNCATE TABLE EXCLUI TODOS OS REGISTROS DA TABELA
-- NÃO TEM WHERE E NÃO TEM COMMIT/ROLLBACK

CREATE TABLE TABELA (
    COD_TESTE INTEGER NOT NULL PRIMARY KEY,
    DATA DATE DEFAULT SYSDATE
);
/*o SYSDATE indica que se nenhuma data for inserida na entrada de dados,
será assumida a data do momento*/

SELECT * FROM TABELA;

INSERT INTO TABELA (COD_TESTE) VALUES (1);
INSERT INTO TABELA (COD_TESTE) VALUES (2);
INSERT INTO TABELA (COD_TESTE) VALUES (3);
INSERT INTO TABELA (COD_TESTE) VALUES (4);

TRUNCATE TABLE TABELA;

































