--------------------
-- CRIANDO VISÕES --
--------------------
--visões são views

-- é uma tabela lógica baseada em uma tabela ou outra visão. 
-- VIEW são SELECTS salvas em forma de OBJETOS
-- podem ser SIMPLES e COMPLEXAS

-- CREATE OR REPLACE // FORCE OR NOFORCE // OR REPLACE (atualiza ou recria)

------------------------------------------------------------------------------

CREATE OR REPLACE VIEW V_ALUNO
AS 
    SELECT COD_ALUNO AS CODIGO, SALARIO, NOME AS ALUNO, ESTADO, CIDADE
    FROM TALUNO
    WHERE ESTADO = 'RS';

-- USANDO A VIEW
SELECT * FROM V_ALUNO
ORDER BY ALUNO;

---

CREATE OR REPLACE VIEW V_CONTRATO_TOP
AS  
    SELECT COD_CONTRATO, DESCONTO
    FROM TCONTRATO
    WHERE DESCONTO > 10;

SELECT * FROM V_CONTRATO_TOP;


-- PARA VISUALIZAR AS VIEWA EXISTENTES E CRIADAS PELO USU�?RIO EM VOGA... 
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;

-- VIEW COM PARÂMETROS DE SA�?DA
CREATE OR REPLACE VIEW V_ALUNO2 (COD, ALUNO, SAL)
AS
    SELECT COD_ALUNO, NOME, SALARIO
    FROM TALUNO;

SELECT * FROM V_ALUNO2
ORDER BY ALUNO;

-- VIEW COMPLEXA
CREATE OR REPLACE VIEW V_CONTRATO
AS
    SELECT  TRUNC(DATA) AS DATA,
            MAX(DESCONTO) MAXIMO,
            AVG(DESCONTO) MEDIA,
            COUNT(*) QTDE 
    FROM TCONTRATO
    GROUP BY TRUNC(DATA);

SELECT * FROM V_CONTRATO;

--VIEW SIMPLES
CREATE OR REPLACE VIEW V_PESSOA_F
AS
    SELECT COD_PESSOA, TIPO, NOME, COD_RUA AS RUA
    FROM TPESSOA
    WHERE TIPO = 'F';

SELECT * FROM V_PESSOA_F;

-- EXEMPLO DE CONSULTA USANDO VIEW J�? CRIADA E MAIS DE UMA TABELA
SELECT  PES.COD_PESSOA AS CODIGO,
        PES.NOME AS PESSOA,
        CID.NOME AS CIDADE,
        RUA.NOME AS RUA
FROM V_PESSOA_F PES, TRUA RUA, TCIDADE CID 
WHERE PES.RUA = RUA.COD_RUA(+)
AND CID.COD_CIDADE = RUA.COD_CIDADE
ORDER BY PES.NOME;

-- OPERAÇÃO DML NA VIEW
CREATE OR REPLACE VIEW VCURSOS1000CK
AS 
    SELECT COD_CURSO, NOME, VALOR
    FROM TCURSO
    WHERE VALOR = 1000
    WITH CHECK OPTION CONSTRAINT VCURSOS1000__CK;

INSERT INTO VCURSOS1000CK (COD_CURSO, NOME, VALOR)
VALUES (52, 'TESTE-y', 999);
/*
Erro a partir da linha : 87 no comando -
INSERT INTO VCURSOS1000CK (COD_CURSO, NOME, VALOR)
VALUES (52, 'TESTE-y', 999)
Relatório de erros -
ORA-01402: violação da cláusula where da view WITH CHECK OPTION

ERRO GERADO DEVIDO AO VALOR INSERIDO SER DIFERENTE DO VALOR DEFINIDO NA VIEW
*/

INSERT INTO VCURSOS1000CK (COD_CURSO, NOME, VALOR)
VALUES (52, 'TESTE-y', 1000);

SELECT * FROM TCURSO;

SELECT * FROM VCURSOS1000CK;

-- DELETE EM VIEW
SELECT * FROM V_ALUNO;

DELETE FROM V_ALUNO WHERE CODIGO = 3;

SELECT * FROM TALUNO;

-- INSERT EM VIEW
INSERT INTO V_ALUNO
VALUES (50,500,'RS','MYLLA', 'TORRES');
/*
Erro a partir da linha : 114 no comando -
INSERT INTO V_ALUNO
VALUES (50,500,'RS','MYLLA', 'TORRES')
Relatório de erros -
ORA-12899: valor muito grande para a coluna "IAREIS"."TALUNO"."ESTADO" (real: 5, máximo: 2)

ERRO DEVIDO AO ESTADO SER A UF, ENTÃO APENAS 2 D�?GITOS
*/
SELECT * FROM V_ALUNO;

INSERT INTO V_ALUNO
VALUES (25,800,'MYLLA','RS','VACARIA');




COMMIT;

-- VAMOS FAZER UM DELETE EM UMA VIEW
-- (NÃO PODE FAZER DML EM VIEW COMPLEXA)
DELETE FROM V_CONTRATO;
/*
Erro a partir da linha : 137 no comando -
DELETE FROM V_CONTRATO
Erro na Linha de Comandos : 137 Coluna : 13
Relatório de erros -
Erro de SQL: ORA-01732: operação de tratamento de dados inválida nesta view
01732. 00000 -  "data manipulation operation not legal on this view"
*Cause:    

ELA É COMPLEXA. O SELECT DELA TEM FUNÇÕES DE GRUPO
*/

-- VIEW SOMENTE LEITURA (NÃO PERMITE DML)
CREATE OR REPLACE VIEW V_ALUNO3
AS 
    SELECT  COD_ALUNO CODIGO,
            NOME ALUNO, CIDADE
    FROM TALUNO
    WHERE ESTADO = 'RS'
    WITH READ ONLY;

-- nÃO PODE EXECUTAR DELETE EM VIEW SOMENTE PARA LEITURA
DELETE FROM V_ALUNO3;
/*
Erro de SQL: ORA-42399: não é possível efetuar uma operação de DML em uma view somente para leitura
*/  

-- EXCLUINDO UMA VISÃO --> VIEW
DROP VIEW V_ALUNO3;

