



--TESTE DE IMPRESSÃO
SELECT * FROM TALUNO;





CREATE OR REPLACE PROCEDURE TUDODO_ALUNO
(pREGISTRO IN OUT TALUNO%ROWTYPE)
IS 
    CURSOR TUDO IS
        SELECT * FROM TALUNO
        WHERE COD_ALUNO = pREGISTRO.COD_ALUNO;
BEGIN
    OPEN TUDO;
    FETCH TUDO INTO pREGISTRO;
    CLOSE TUDO;
END;



SELECT * FROM TALUNO;




DECLARE 
    REGISTRO TALUNO%ROWTYPE;
    X DATE;
BEGIN 
    REGISTRO.COD_ALUNO := 11;
    --vID := TRUNC(SYSDATE) - TRUNC(REGISTRO.NASCIMENTO);
    --vID := SYSDATE - REGISTRO.NASCIMENTO;
    --vID := TRUNC(SYSDATE) - TRUNC(REGISTRO.NASCIMENTO);
    TUDODO_ALUNO(REGISTRO);
    DBMS_OUTPUT.PUT_LINE('NOME: '||REGISTRO.NOME);
    DBMS_OUTPUT.PUT_LINE(REGISTRO.CIDADE||' - '||REGISTRO.ESTADO);
    --DBMS_OUTPUT.PUT_LINE('DATA DE NASCIMENTO: '||REGISTRO.NASCIMENTO||' ('||vID||' ANOS)');
    DBMS_OUTPUT.PUT_LINE('DATA DE NASCIMENTO: '||REGISTRO.NASCIMENTO||' ('||X||' ANOS)');
    /*DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE(REGISTRO.NOME);
    DBMS_OUTPUT.PUT_LINE(REGISTRO.CIDADE);
    DBMS_OUTPUT.PUT_LINE(REGISTRO.CEP);
    DBMS_OUTPUT.PUT_LINE(REGISTRO.ESTADO);
    DBMS_OUTPUT.PUT_LINE(REGISTRO.SALARIO);
    DBMS_OUTPUT.PUT_LINE(SYSDATE - REGISTRO.NASCIMENTO);*/
END;