
<!-- ------------------------------------- -->

SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO;

SELECT COD_ALUNO AS "Código", NOME AS "Nome do Aluno" 
FROM TALUNO;

<!--
    DISTINCT RETIRA LINHAS DUPLICADAS
    TODAS AS COLUNAS TEM QUE SER IGUAIS
-->

SELECT * FROM TALUNO;

SELECT CIDADE FROM TALUNO;

SELECT DISTINCT CIDADE FORM TALUNO;

<!-- Não agrupa pois COD_ALUNO diferente -->

SELECT DISTINCT CIDADE, COD_ALUNO 
FROM TALUNO
ORDER BY CIDADE;

<!-- REALIZANDO CÁLCULOS NA TABELA -->

SELECT  NOME AS CURSO,
        VALOR,
        VALOR/CARGA_HORARIA,
        VALOR/CARGA_HORÁRIA AS VALOR_HORA
FROM TCURSO
ORDER BY VALOR_HORA;


SELECT  NOME AS CURSO,
        VALOR,
        VALOR/CARGA_HORARIA,
        Round(VALOR/CARGA_HORÁRIA,2) AS VALOR_HORA
FROM TCURSO
ORDER BY VALOR_HORA;
/* Apelido de coluna só funciona em ORDER BY*/

<!-- -------CONCATEÇÃO utilizando pipe duplo ||------- -->

SELECT COD_ALUNO || ' - ' || NOME || ' // ' || CIDADE AS ALUNO 
FROM TALUNO 
ORDER BY COD_ALUNO
