



--TESTE DE IMPRESSÃO
SELECT * FROM TALUNO;





CREATE OR REPLACE PROCEDURE CONSULTA_ALUNO2
(pREGISTRO IN OUT TALUNO%ROWTYPE)
IS 
    CURSOR CSQL IS
        SELECT * FROM TALUNO
        WHERE COD_ALUNO = pREGISTRO.COD_ALUNO;
BEGIN
    OPEN CSQL;
    FETCH CSQL INTO pREGISTRO;
    CLOSE CSQL;
END;





SELECT * FROM TALUNO;

DECLARE 
    REGISTRO TALUNO%ROWTYPE;
    vID INTEGER;
BEGIN 
    REGISTRO.COD_ALUNO := 1;
    CONSULTA_ALUNO2(REGISTRO);
    DBMS_OUTPUT.PUT_LINE('NOME: '||REGISTRO.NOME);
    DBMS_OUTPUT.PUT_LINE(REGISTRO.CIDADE||' - '||REGISTRO.ESTADO);
    DBMS_OUTPUT.PUT_LINE(
        'DATA DE NASCIMENTO: '||REGISTRO.NASCIMENTO||' ('||ID||' ANOS)'
    );
END;