--------------------
-- SUB-CONSULTAS --
--------------------

SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >= (
    SELECT VALOR
    FROM TCURSO
    WHERE COD_CURSO =3
);
/*na sub-consulta não pode retornar mais do que um resultado, pois ela
é a base da comparação*/

-- ERRADO (abaixo um exemplo onde a pré-consulta retorna 3 valores)
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >= (
    SELECT VALOR
    FROM TCURSO
    WHERE VALOR > 500
);
/*
Relatório de erros -
ORA-01427: a subconsulta de uma única linha retorna mais de uma linha
*/

SELECT * FROM TALUNO;

-- TODOS OS ALUNOS DA MESMA CIDADE DEO ALUNO ESCOLHIDO CFE COD_ALUNO
-- MENOS O PRÓPRIO ALUNO

SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
WHERE   CIDADE = 
        (SELECT CIDADE
        FROM TALUNO
        WHERE COD_ALUNO = 2)
AND COD_ALUNO <> 2;
/*o aluno 2 é de Canoas*/

-- TODOS OS ALUNOS DA MESMA CIDADE E ESTADO DO ALUNO COD_ALUNO = 5
-- COM EXCESSÃO DO P´ROPRIO ALUNO 5

SELECT COD_ALUNO, NOME, CIDADE, ESTADO
FROM TALUNO
WHERE   (CIDADE, ESTADO) =
        (SELECT CIDADE, ESTADO
        FROM TALUNO
        WHERE COD_ALUNO = 5)
AND COD_ALUNO <> 5;
/*o aluno 5 é de Porto Alegre*/

-- SOMA DE TODOS OS ITENS, E MOSTRAR SOMENTE OS QUE O VALOR MÍNIMO
-- SEJA MAIOR QUE O VALOR MÉDIO DOS CURSOS

SELECT COD_CURSO, MIN(VALOR), SUM(VALOR), COUNT(*) QTDE
FROM TITEM
WHERE COD_CURSO > 0
GROUP BY COD_CURSO
HAVING MIN(VALOR) >= (SELECT AVG(VALOR) FROM TCURSO)
ORDER BY COD_CURSO; 

-- SOMA O TOTAL DE CONSTRATOS POR ALUNO
-- E MOSTRA SOMENTE AQUELES CUJO MENOR CONTRATO
-- SEJA MAIOR QUE O VALOR MÉDIO DO CURSO

SELECT COD_ALUNO, MIN(TOTAL) MINIMO, SUM(TOTAL) TOTAL
FROM TCONTRATO
GROUP BY COD_ALUNO
HAVING MINIMO > (SELECT AVG(VALOR) FROM TCURSO);

-- TODOS OS CURSOS QUE ESTÃO NA TABELA DE ITENS (VENDIDOS)

SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM)
ORDER BY COD_CURSO;
/*
sub-select só pode trazer um registro dependendo do OPERADOR utilizado
Com o operador IN ele traz registros dentro de um CONJUNTO
*/

-- TODOS OS CURSOS QUE NÃO ESTÃO NA TABELA DE ITENS,
-- OU SEJA, OS CURSOS NÃO VENDIDOS

SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM)
ORDER BY NOME;

/*PARA MELHOR ENTENDER O QUE SIGNIFICA O GRUPO QUE CORRESPONDE...*/
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO WHERE COD_CURSO IN (1,2,3,4);

/*ABAIXO UMA OUTRA FORMA DE ESCREVER O EXEMPLO ACIMA*/
-- mas só se utiliza desta forma se vc souber os códigos
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO = 1
OR COD_CURSO =2
OR COD_CURSO =3
OR COD_CURSO =4;

-- TODOS OS CURSOS QUE FORAM VENDIDOS PELO VALOR PADRÃO QUE CONSTA NA TABELA CURSO
-- PQ NA TABELA ITEM PODE TER OCORRIDO PROMOÇÃO OU DESCONTO E O VALOR SER DIFERENTE
-- ENTÃO ESTA PESQUISA BUSCA OS CURSOS VENDIDOS PELO VALOR CORRETO
SELECT * FROM TITEM 
WHERE COD_CURSO, VALOR IN (SELECT COD_CURSO, VALOR FROM TCURSO)

-- SUBCONSULTA NA CLAUSULA FROM

SELECT  ITE.COD_CONTRATO, ITE.VALOR, ITE.COD_CURSO,
        CUR.COD_CURSO, CUR.VALOR
FROM    TITEM ITE,
        (SELECT COD_CURSO, VALOR
        FROM TCURSO
        WHERE VALOR > 500) CUR
WHERE CUR.COD_CURSO = ITE.COD_CURSO;




