----------------------- 
-- MANIPULANDO DADOS --
-----------------------

-- INSERT - UPDATE - DELETE --

SELECT * FROM TDESCONTO;

INSERT INTO TDESCONTO (CLASSE, INFERIOR, SUPERIOR)
VALUES ('&cla', &inf, &sup);

SELECT * FROM TDESCONTO
WHERE CLASSE = '&cla';

UPDATE TDESCONTO SET 
INFERIOR = &inf,
SUPERIOR = &sup 
WHERE CLASSE = '&cla';

DELETE FROM TDESCONTO
WHERE CLASSE = '&cla';

-- CRIAR UMA NOVA TABELA TENDO POR BASE UMA JÁ EXISTENTE

CREATE TABLE TDESCONTO2 AS (SELECT * FROM TDESCONTO);

SELECT * FROM TDESCONTO2;

COMMIT;

---

DELETE FROM TDESCONTO2;

ROLLBACK;

TRUNCATE TABLE TDESCONTO2;
/*dELETA TODOS OS REGISTROS DA TABELA. nÃO TEM CLAUSULA WHERE E NÃO TEM ROOLBACK*/

-- SAVEPOINT
-- cria um ponto de restauração

COMMIT;

SELECT * FROM TDESCONTO;

SAVEPOINT UPD_B;

UPDATE TDESCONTO SET 
SUPERIOR = 88
WHERE CLASSE = 'B';

SAVEPOINT UPD_A;

UPDATE TDESCONTO SET 
SUPERIOR = 99
WHERE CLASSE = 'A';

SAVEPOINT INS_OK;

INSERT INTO TDESCONTO (CLASSE, INFERIOR, SUPERIOR)
VALUES ('&cla', &inf, &sup);

-- RESTAURAR ATÉ O PONTO DE SALVAMENTO

ROLLBACK TO SAVEPOINT INS_OK;
ROLLBACK TO SAVEPOINT UPD_B;
ROLLBACK TO SAVEPOINT UPD_A;

-- EXCLUIR A TABELA

DROP TABLE TDESCONTO2;


