DECLARE 
    VIDADE TALUNO.NASCIMENTO%TYPE;
    VDT_NASCEU TALUNO.NASCIMENTO%TYPE;
    VDT_HOJE DATE := TRUNC(SYSDATE);
    VCOD_ALUNO TALUNO.COD_ALUNO%TYPE    :=  &CODIGO;
BEGIN
    SELECT  NASCIMENTO 
    INTO    VDT_NASCEU
    FROM    TALUNO
    WHERE   COD_ALUNO = VCOD_ALUNO;
    --VIDADE := TO_DATE(VDT_HOJE - VDT_NASCEU);
    VIDADE := VDT_HOJE - VDT_NASCEU;
    Dbms_Output.Put_Line(VIDADE);
END;
/*
Relatório de erros -
ORA-06550: linha 12, coluna 15:
PLS-00382: a expressão é do tipo incorreto
ORA-06550: linha 12, coluna 5:
PL/SQL: Statement ignored
06550. 00000 -  "line %s, column %s:\n%s"
*Cause:    Usually a PL/SQL compilation error.
*/

DECLARE 
    VIDADE TALUNO.NASCIMENTO%TYPE;
    VDT_NASCEU TALUNO.NASCIMENTO%TYPE;
    VDT_HOJE DATE := TRUNC(SYSDATE);
    VCOD_ALUNO TALUNO.COD_ALUNO%TYPE    :=  &CODIGO;
BEGIN
    SELECT  NASCIMENTO 
    INTO    VDT_NASCEU
    FROM    TALUNO
    WHERE   COD_ALUNO = VCOD_ALUNO;
    --VIDADE := TO_DATE(VDT_HOJE - VDT_NASCEU);
    VIDADE := VDT_HOJE - VDT_NASCEU;
    Dbms_Output.Put_Line(VIDADE);
END;


DECLARE 
    VIDADE TALUNO.NASCIMENTO%TYPE;
    VDT_NASCEU TALUNO.NASCIMENTO%TYPE;
    VDT_HOJE DATE := TRUNC(SYSDATE);
    VCOD_ALUNO TALUNO.COD_ALUNO%TYPE    :=  &CODIGO;
BEGIN
    SELECT  NASCIMENTO 
    INTO    VDT_NASCEU
    FROM    TALUNO
    WHERE   COD_ALUNO = VCOD_ALUNO;
    --VIDADE := TO_DATE(VDT_HOJE - VDT_NASCEU);
    VIDADE := VDT_HOJE


